### ISSUE TITLE
Swift package manager support

### ISSUE THREAD

**Issue by chrs1885** [chrs1885/Capable#12]

**Comment by dehlen** [comment]
I'd love to have a look at this. However I am not quite sure what should be supported ?
As the readme state from the swift package manager project:

> Note that at this time the Package Manager has no support for iOS, watchOS, or tvOS platforms.

So currently I can't see how Swift Package Manager could be supported ?

**Comment by chrs1885** [comment]
I was having a look at a [tutorial](https://www.ralfebert.de/ios-examples/xcode/ios-dependency-management-with-swift-package-manager/) lately, and it seems like there is a way to create iOS frameworks that support swift package manager... packages. However, as long as there's no official iOS support, I'll focus on adding macOS support for now. Let's move this one to 0.4.0. 👍

**Comment by chrs1885** [comment]
Added in #19
