### ISSUE TITLE
Capable framework not found in Example application

### ISSUE THREAD

**Issue by dehlen** [chrs1885/Capable#4]
Currently the example application can not be run out-of-the-box. At the current state the application will show an error when compiling that it "cannot find Capable". I think the product of the included Xcode project should either be linked in the "Linked Binaries With Libraries" phase or should be included via Carthage/Cocoapods. The first approach might be more useful since this way the iteration of the Example project could be a lot quicker.

**Comment by chrs1885** [comment]
Fixed in #14
