### ISSUE TITLE
Replace allValues with CaseIterable allCases

### ISSUE THREAD

**Issue by dehlen** [chrs1885/Capable#6]
With Swift 4.2 (see Proposal [SE-0194](https://github.com/apple/swift-evolution/blob/master/proposals/0194-derived-collection-of-enum-cases.md)) a new protocol is introduced called CaseIterable which automatically generates all available cases for an enum. This way the allValues method could be deleted. However I guess we have to wait for the new Xcode 10 to try this new language feature. Whenever I get my hands on the new beta I am happy to help with a PR. I just wanted to open an issue in order to document this.

**Comment by chrs1885** [comment]
Thanks @dehlen for your input. This has been added with #28.
