### ISSUE TITLE
Build error while importing Capable 2.0.0 using SPM

### ISSUE THREAD

**Issue by jtouzy** [chrs1885/Capable#64]
> Please fill out all lines starting with a 📝 when filing a bug to give us an idea of what exactly went wrong.

## What did you do?
📝 Impoorting Capable using SPM, at version 2.0.0

## What did you expect to happen?
📝 The project to build successfully 😅 

## What happened instead?
📝 Error when `DifferentiateWithoutColor` observation is created, on iOS platforms :
<img width="1286" alt="Screenshot 2022-02-06 at 18 41 56" src="https://user-images.githubusercontent.com/5709133/152693740-a13bb859-659d-454e-b5e7-8b1b395e158b.png">
The `NSNotification.Name(rawValue:)` wrapping is too much, just use directly `UIAccessibility.differentiateWithoutColorDidChangeNotification` for observer.

## Setup
📝 Just import Capable 2.0.0 using SPM.

**Comment by jtouzy** [comment]
Ok, it's seems to be fixed in develop branch.
https://github.com/chrs1885/Capable/commit/6b107d28ce2ac93c3e863557963dff3ff4e1a9f5
Could you please publish a new release in master with this fix ?

**Comment by jtouzy** [comment]
No matter. Complex projet, for something not that complex. Closing this.

**Comment by chrs1885** [comment]
FYI @jtouzy https://github.com/chrs1885/Capable/releases/tag/2.0.1
