### ISSUE TITLE
Need FullKeyboardAccess Check for iOS

### ISSUE THREAD

**Issue by ThruralDev** [chrs1885/Capable#66]
## What kind of feature would you like to see?
I would like to see a feature to check, if "Full Keyboard Access" is turned on iOS.

## How does it work in detail?
Feature can check if "Full Keyboard Access" is turned on in Settings > Accessibility > Keyboards on iOS.

## What does the API look like?
It would look like:
let capable = Capable(withFeatures: [. fullKeyboardAccess])
let isFeatureEnabled: Bool = capable.isFeatureEnable(feature: . fullKeyboardAccess)

Just the way it works on MacOS. I've tried it on a MacOS destination target and that is exactly what I want and need for iOS.

## Any existing projects that do something similiar?
Nothing found..
Would appreciate any explanation or tips, what's the difference between MacOS and iOS just for understanding.

**Comment by chrs1885** [comment]
@ThruralDev As of today, iOS doesn't provide a direct API for third-party apps to check whether the "Full Keyboard Access" setting is enabled in the "Settings > Accessibility > Keyboards" path of a device.

For privacy and security reasons, Apple limits the amount of information that third-party apps can access regarding the user's system settings. Accessibility features typically fall within this category of protected settings.
